/**
0) When the page is loaded, everything inside #content should be hidden. The LOGIN FORM should also be hidden.
**/
https://jsfiddle.net/0ecbf2qn/308/

/**
1) Write a function that will make a fully collapsible/expandable menu out of #nav_main.
Since this is a function, it should be reusable. I should be able to make multiple
collapsible navs on the same page. When the menu is shown, use Javascript to
change the text of the "toggle" link to say "Hide Menu." And the menu should be collapsed whent he page loads. 
Design the menu to look like a real menu...
**/
function click(clickedElement, targetElement) {
	var tar = document.querySelector(targetElement);
  var cli = document.querySelector(clickedElement);
  
  tar.classList.toggle('hidden');
  cli.addEventListener("click", function hide() {
    tar.classList.toggle('hidden');
    if (tar.classList.contains('hidden')) {
  		cli.innerHTML = "Show Menu";
  	}
    else {
    	cli.innerHTML = "Hide Menu";
    };
  })
  
}


click("#menu_toggle", "#list");

/**
2) When the user clicks "Log In," if the correct username/password is submitted, go ahead and display #content for them. If not, display a message that says "Sorry, please try again."
**/
function logMeIn() {
	var link = document.querySelector("#loginLink");
  link.addEventListener("click", function hide() {
  document.querySelector("#login").classList.remove("hidden")
  })
}

function compare() {
var usr = document.getElementById("usr_name").value;
var pass = document.getElementById("password").value;
  if ((usr == "mel") && (pass == "vin")) {
    document.getElementById("content").classList.remove("hidden")}
    
  else {
 		document.getElementById("message").innerHTML = "Sorry please try again."
  };
};


document.querySelector("#submitLogin").addEventListener("click", function() {
	compare();
});
logMeIn();
/**
3) Create a reusable object function that will represent a book. It should accept a Title, Author, Publication Date, Price, and Status (checkedIn or checkedOut). Create a function called feature() for this object -- it will create a div inside the #featuredBooks div which will display that book's information. Add a CSS class to that indiviudal book's div for checkedIn/checkedOut

**/
function book(title, author, publicationDate, price, status) {
  this.title = title;
  this.author = author; 
  this.publicationDate = publicationDate; 
  this.price = price;
  this.status = status;
  this.feature = function() { 
  
  
  var feat = document.getElementById("featuredBooks");
  
  var createdDiv = document.createElement('div');
  
  
  var createH1 = document.createElement("h1");
  var text = document.createTextNode(this.title);
  createH1.appendChild(text);
  createdDiv.appendChild(createH1);
  
  var createH2 = document.createElement("h2");
  var text2 = document.createTextNode(this.author);
  createH2.appendChild(text2);
  createdDiv.appendChild(createH2);
  
  var createH3 = document.createElement("h3");
  var text3 = document.createTextNode(this.publicationDate);
  createH3.appendChild(text3);
  createdDiv.appendChild(createH3);
  
  var createH4 = document.createElement("h4");
  var text4 = document.createTextNode(this.price);
  createH4.appendChild(text4);
  createdDiv.appendChild(createH4);
  
  var createH5 = document.createElement("h5");
  var text5 = document.createTextNode(this.status);
  createH5.appendChild(text5);
  createdDiv.appendChild(createH5);
  createdDiv.classList.add(this.status);
  
  
  feat.appendChild(createdDiv);
  
           createdDiv.addEventListener("click", function(){
          if (createdDiv.classList.contains("checkedOut")) {
          createdDiv.classList.toggle("checkedOut");
          createdDiv.classList.toggle("checkedIn");
          } else if (createdDiv.classList.contains("checkedIn")) {
          createdDiv.classList.toggle("checkedOut");
          createdDiv.classList.toggle("checkedIn");
          }
        });
}
}


var HarryPotter = new book("Philo Stone", "JK Rowling", "2000", 23, "checkedOut");
var HarryPotter2 = new book("Second Book", "JK Rowling", "2002", 28, "checkedIn");
var HarryPotter3 = new book("Third Book", "JK Rowling", "2010", 33, "checkedOut");
var HarryPotter4 = new book("How many are there again?", "JK Rowling", "2012", 43, "checkedOut");

HarryPotter.feature();
HarryPotter2.feature();
HarryPotter3.feature();
HarryPotter4.feature();


/**
4) Create at least four books and feature them. Write some CSS to make it look like we're actually featuring some books. Make at least one of them checkedOut, and make sure you have some CSS to indicate as such. When I click on one of the divs generated by the book, it should change to "checked out" or "checked in," whichever it currently isn't.
**/



